// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lane.proto

#ifndef PROTOBUF_lane_2eproto__INCLUDED
#define PROTOBUF_lane_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "id.pb.h"
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace hdmap_proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lane_2eproto();
void protobuf_AssignDesc_lane_2eproto();
void protobuf_ShutdownFile_lane_2eproto();

class Lane;

// ===================================================================

class Lane : public ::google::protobuf::Message {
 public:
  Lane();
  virtual ~Lane();

  Lane(const Lane& from);

  inline Lane& operator=(const Lane& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Lane& default_instance();

  void Swap(Lane* other);

  // implements Message ----------------------------------------------

  Lane* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Lane& from);
  void MergeFrom(const Lane& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .hdmap_proto.Id id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::hdmap_proto::Id& id() const;
  inline ::hdmap_proto::Id* mutable_id();
  inline ::hdmap_proto::Id* release_id();
  inline void set_allocated_id(::hdmap_proto::Id* id);

  // repeated .hdmap_proto.CurveLine lines = 2;
  inline int lines_size() const;
  inline void clear_lines();
  static const int kLinesFieldNumber = 2;
  inline const ::hdmap_proto::CurveLine& lines(int index) const;
  inline ::hdmap_proto::CurveLine* mutable_lines(int index);
  inline ::hdmap_proto::CurveLine* add_lines();
  inline const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::CurveLine >&
      lines() const;
  inline ::google::protobuf::RepeatedPtrField< ::hdmap_proto::CurveLine >*
      mutable_lines();

  // @@protoc_insertion_point(class_scope:hdmap_proto.Lane)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::hdmap_proto::Id* id_;
  ::google::protobuf::RepeatedPtrField< ::hdmap_proto::CurveLine > lines_;
  friend void  protobuf_AddDesc_lane_2eproto();
  friend void protobuf_AssignDesc_lane_2eproto();
  friend void protobuf_ShutdownFile_lane_2eproto();

  void InitAsDefaultInstance();
  static Lane* default_instance_;
};
// ===================================================================


// ===================================================================

// Lane

// required .hdmap_proto.Id id = 1;
inline bool Lane::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Lane::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Lane::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Lane::clear_id() {
  if (id_ != NULL) id_->::hdmap_proto::Id::Clear();
  clear_has_id();
}
inline const ::hdmap_proto::Id& Lane::id() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Lane.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
inline ::hdmap_proto::Id* Lane::mutable_id() {
  set_has_id();
  if (id_ == NULL) id_ = new ::hdmap_proto::Id;
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Lane.id)
  return id_;
}
inline ::hdmap_proto::Id* Lane::release_id() {
  clear_has_id();
  ::hdmap_proto::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline void Lane::set_allocated_id(::hdmap_proto::Id* id) {
  delete id_;
  id_ = id;
  if (id) {
    set_has_id();
  } else {
    clear_has_id();
  }
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Lane.id)
}

// repeated .hdmap_proto.CurveLine lines = 2;
inline int Lane::lines_size() const {
  return lines_.size();
}
inline void Lane::clear_lines() {
  lines_.Clear();
}
inline const ::hdmap_proto::CurveLine& Lane::lines(int index) const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Lane.lines)
  return lines_.Get(index);
}
inline ::hdmap_proto::CurveLine* Lane::mutable_lines(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Lane.lines)
  return lines_.Mutable(index);
}
inline ::hdmap_proto::CurveLine* Lane::add_lines() {
  // @@protoc_insertion_point(field_add:hdmap_proto.Lane.lines)
  return lines_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::CurveLine >&
Lane::lines() const {
  // @@protoc_insertion_point(field_list:hdmap_proto.Lane.lines)
  return lines_;
}
inline ::google::protobuf::RepeatedPtrField< ::hdmap_proto::CurveLine >*
Lane::mutable_lines() {
  // @@protoc_insertion_point(field_mutable_list:hdmap_proto.Lane.lines)
  return &lines_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap_proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lane_2eproto__INCLUDED
