// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "map.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hdmap_proto {

namespace {

const ::google::protobuf::Descriptor* Header_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Header_reflection_ = NULL;
const ::google::protobuf::Descriptor* Map_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Map_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_map_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_map_2eproto() {
  protobuf_AddDesc_map_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "map.proto");
  GOOGLE_CHECK(file != NULL);
  Header_descriptor_ = file->message_type(0);
  static const int Header_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, projection_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, low_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, high_),
  };
  Header_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Header_descriptor_,
      Header::default_instance_,
      Header_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _has_bits_[0]),
      -1,
      -1,
      sizeof(Header),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _internal_metadata_),
      -1);
  Map_descriptor_ = file->message_type(1);
  static const int Map_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, sections_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, zones_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, obstacles_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, segpoint_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, slopes_),
  };
  Map_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Map_descriptor_,
      Map::default_instance_,
      Map_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, _has_bits_[0]),
      -1,
      -1,
      sizeof(Map),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_map_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Header_descriptor_, &Header::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Map_descriptor_, &Map::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_map_2eproto() {
  delete Header::default_instance_;
  delete Header_reflection_;
  delete Map::default_instance_;
  delete Map_reflection_;
}

void protobuf_AddDesc_map_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_map_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::hdmap_proto::protobuf_AddDesc_geometry_2eproto();
  ::hdmap_proto::protobuf_AddDesc_section_2eproto();
  ::hdmap_proto::protobuf_AddDesc_object_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmap.proto\022\013hdmap_proto\032\016geometry.proto"
    "\032\rsection.proto\032\014object.proto\"\204\001\n\006Header"
    "\022\017\n\007version\030\001 \001(\t\022\014\n\004date\030\002 \001(\t\022\022\n\nproje"
    "ction\030\003 \001(\t\022\"\n\003low\030\004 \002(\0132\025.hdmap_proto.V"
    "ector3d\022#\n\004high\030\005 \002(\0132\025.hdmap_proto.Vect"
    "or3d\"\364\001\n\003Map\022#\n\006header\030\001 \001(\0132\023.hdmap_pro"
    "to.Header\022&\n\010sections\030\002 \003(\0132\024.hdmap_prot"
    "o.Section\022 \n\005zones\030\003 \003(\0132\021.hdmap_proto.Z"
    "one\022(\n\tobstacles\030\004 \003(\0132\025.hdmap_proto.Obs"
    "tacle\022,\n\010segPoint\030\005 \003(\0132\032.hdmap_proto.Se"
    "manticPoint\022&\n\006slopes\030\006 \001(\0132\026.hdmap_prot"
    "o.SlopeSets", 451);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "map.proto", &protobuf_RegisterTypes);
  Header::default_instance_ = new Header();
  Map::default_instance_ = new Map();
  Header::default_instance_->InitAsDefaultInstance();
  Map::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_map_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_map_2eproto {
  StaticDescriptorInitializer_map_2eproto() {
    protobuf_AddDesc_map_2eproto();
  }
} static_descriptor_initializer_map_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Header::kVersionFieldNumber;
const int Header::kDateFieldNumber;
const int Header::kProjectionFieldNumber;
const int Header::kLowFieldNumber;
const int Header::kHighFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Header::Header()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap_proto.Header)
}

void Header::InitAsDefaultInstance() {
  low_ = const_cast< ::hdmap_proto::Vector3d*>(&::hdmap_proto::Vector3d::default_instance());
  high_ = const_cast< ::hdmap_proto::Vector3d*>(&::hdmap_proto::Vector3d::default_instance());
}

Header::Header(const Header& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hdmap_proto.Header)
}

void Header::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  projection_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  low_ = NULL;
  high_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:hdmap_proto.Header)
  SharedDtor();
}

void Header::SharedDtor() {
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  projection_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete low_;
    delete high_;
  }
}

void Header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Header::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Header_descriptor_;
}

const Header& Header::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2eproto();
  return *default_instance_;
}

Header* Header::default_instance_ = NULL;

Header* Header::New(::google::protobuf::Arena* arena) const {
  Header* n = new Header;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:hdmap_proto.Header)
  if (_has_bits_[0 / 32] & 31u) {
    if (has_version()) {
      version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_date()) {
      date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_projection()) {
      projection_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_low()) {
      if (low_ != NULL) low_->::hdmap_proto::Vector3d::Clear();
    }
    if (has_high()) {
      if (high_ != NULL) high_->::hdmap_proto::Vector3d::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap_proto.Header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string version = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hdmap_proto.Header.version");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_date;
        break;
      }

      // optional string date = 2;
      case 2: {
        if (tag == 18) {
         parse_date:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_date()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->date().data(), this->date().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hdmap_proto.Header.date");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_projection;
        break;
      }

      // optional string projection = 3;
      case 3: {
        if (tag == 26) {
         parse_projection:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_projection()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->projection().data(), this->projection().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hdmap_proto.Header.projection");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_low;
        break;
      }

      // required .hdmap_proto.Vector3d low = 4;
      case 4: {
        if (tag == 34) {
         parse_low:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_low()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_high;
        break;
      }

      // required .hdmap_proto.Vector3d high = 5;
      case 5: {
        if (tag == 42) {
         parse_high:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_high()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap_proto.Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap_proto.Header)
  return false;
#undef DO_
}

void Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap_proto.Header)
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->version(), output);
  }

  // optional string date = 2;
  if (has_date()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.date");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->date(), output);
  }

  // optional string projection = 3;
  if (has_projection()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->projection().data(), this->projection().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.projection");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->projection(), output);
  }

  // required .hdmap_proto.Vector3d low = 4;
  if (has_low()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->low_, output);
  }

  // required .hdmap_proto.Vector3d high = 5;
  if (has_high()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->high_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap_proto.Header)
}

::google::protobuf::uint8* Header::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hdmap_proto.Header)
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->version(), target);
  }

  // optional string date = 2;
  if (has_date()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.date");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->date(), target);
  }

  // optional string projection = 3;
  if (has_projection()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->projection().data(), this->projection().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hdmap_proto.Header.projection");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->projection(), target);
  }

  // required .hdmap_proto.Vector3d low = 4;
  if (has_low()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->low_, false, target);
  }

  // required .hdmap_proto.Vector3d high = 5;
  if (has_high()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->high_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap_proto.Header)
  return target;
}

int Header::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:hdmap_proto.Header)
  int total_size = 0;

  if (has_low()) {
    // required .hdmap_proto.Vector3d low = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->low_);
  }

  if (has_high()) {
    // required .hdmap_proto.Vector3d high = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->high_);
  }

  return total_size;
}
int Header::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:hdmap_proto.Header)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000018) ^ 0x00000018) == 0) {  // All required fields are present.
    // required .hdmap_proto.Vector3d low = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->low_);

    // required .hdmap_proto.Vector3d high = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->high_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->version());
    }

    // optional string date = 2;
    if (has_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->date());
    }

    // optional string projection = 3;
    if (has_projection()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->projection());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Header::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hdmap_proto.Header)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Header* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Header>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hdmap_proto.Header)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hdmap_proto.Header)
    MergeFrom(*source);
  }
}

void Header::MergeFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hdmap_proto.Header)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_has_version();
      version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
    }
    if (from.has_date()) {
      set_has_date();
      date_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.date_);
    }
    if (from.has_projection()) {
      set_has_projection();
      projection_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.projection_);
    }
    if (from.has_low()) {
      mutable_low()->::hdmap_proto::Vector3d::MergeFrom(from.low());
    }
    if (from.has_high()) {
      mutable_high()->::hdmap_proto::Vector3d::MergeFrom(from.high());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Header::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hdmap_proto.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hdmap_proto.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000018) != 0x00000018) return false;

  if (has_low()) {
    if (!this->low_->IsInitialized()) return false;
  }
  if (has_high()) {
    if (!this->high_->IsInitialized()) return false;
  }
  return true;
}

void Header::Swap(Header* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Header::InternalSwap(Header* other) {
  version_.Swap(&other->version_);
  date_.Swap(&other->date_);
  projection_.Swap(&other->projection_);
  std::swap(low_, other->low_);
  std::swap(high_, other->high_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Header::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Header_descriptor_;
  metadata.reflection = Header_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Header

// optional string version = 1;
bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Header::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
void Header::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_version();
}
 const ::std::string& Header::version() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Header.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hdmap_proto.Header.version)
}
 void Header::set_version(const char* value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hdmap_proto.Header.version)
}
 void Header::set_version(const char* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hdmap_proto.Header.version)
}
 ::std::string* Header::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Header.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Header::release_version() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Header.version)
  clear_has_version();
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Header.version)
}

// optional string date = 2;
bool Header::has_date() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Header::set_has_date() {
  _has_bits_[0] |= 0x00000002u;
}
void Header::clear_has_date() {
  _has_bits_[0] &= ~0x00000002u;
}
void Header::clear_date() {
  date_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_date();
}
 const ::std::string& Header::date() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Header.date)
  return date_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_date(const ::std::string& value) {
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hdmap_proto.Header.date)
}
 void Header::set_date(const char* value) {
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hdmap_proto.Header.date)
}
 void Header::set_date(const char* value, size_t size) {
  set_has_date();
  date_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hdmap_proto.Header.date)
}
 ::std::string* Header::mutable_date() {
  set_has_date();
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Header.date)
  return date_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Header::release_date() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Header.date)
  clear_has_date();
  return date_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_allocated_date(::std::string* date) {
  if (date != NULL) {
    set_has_date();
  } else {
    clear_has_date();
  }
  date_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), date);
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Header.date)
}

// optional string projection = 3;
bool Header::has_projection() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Header::set_has_projection() {
  _has_bits_[0] |= 0x00000004u;
}
void Header::clear_has_projection() {
  _has_bits_[0] &= ~0x00000004u;
}
void Header::clear_projection() {
  projection_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_projection();
}
 const ::std::string& Header::projection() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Header.projection)
  return projection_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_projection(const ::std::string& value) {
  set_has_projection();
  projection_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hdmap_proto.Header.projection)
}
 void Header::set_projection(const char* value) {
  set_has_projection();
  projection_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hdmap_proto.Header.projection)
}
 void Header::set_projection(const char* value, size_t size) {
  set_has_projection();
  projection_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hdmap_proto.Header.projection)
}
 ::std::string* Header::mutable_projection() {
  set_has_projection();
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Header.projection)
  return projection_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Header::release_projection() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Header.projection)
  clear_has_projection();
  return projection_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Header::set_allocated_projection(::std::string* projection) {
  if (projection != NULL) {
    set_has_projection();
  } else {
    clear_has_projection();
  }
  projection_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), projection);
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Header.projection)
}

// required .hdmap_proto.Vector3d low = 4;
bool Header::has_low() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Header::set_has_low() {
  _has_bits_[0] |= 0x00000008u;
}
void Header::clear_has_low() {
  _has_bits_[0] &= ~0x00000008u;
}
void Header::clear_low() {
  if (low_ != NULL) low_->::hdmap_proto::Vector3d::Clear();
  clear_has_low();
}
const ::hdmap_proto::Vector3d& Header::low() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Header.low)
  return low_ != NULL ? *low_ : *default_instance_->low_;
}
::hdmap_proto::Vector3d* Header::mutable_low() {
  set_has_low();
  if (low_ == NULL) {
    low_ = new ::hdmap_proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Header.low)
  return low_;
}
::hdmap_proto::Vector3d* Header::release_low() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Header.low)
  clear_has_low();
  ::hdmap_proto::Vector3d* temp = low_;
  low_ = NULL;
  return temp;
}
void Header::set_allocated_low(::hdmap_proto::Vector3d* low) {
  delete low_;
  low_ = low;
  if (low) {
    set_has_low();
  } else {
    clear_has_low();
  }
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Header.low)
}

// required .hdmap_proto.Vector3d high = 5;
bool Header::has_high() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Header::set_has_high() {
  _has_bits_[0] |= 0x00000010u;
}
void Header::clear_has_high() {
  _has_bits_[0] &= ~0x00000010u;
}
void Header::clear_high() {
  if (high_ != NULL) high_->::hdmap_proto::Vector3d::Clear();
  clear_has_high();
}
const ::hdmap_proto::Vector3d& Header::high() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Header.high)
  return high_ != NULL ? *high_ : *default_instance_->high_;
}
::hdmap_proto::Vector3d* Header::mutable_high() {
  set_has_high();
  if (high_ == NULL) {
    high_ = new ::hdmap_proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Header.high)
  return high_;
}
::hdmap_proto::Vector3d* Header::release_high() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Header.high)
  clear_has_high();
  ::hdmap_proto::Vector3d* temp = high_;
  high_ = NULL;
  return temp;
}
void Header::set_allocated_high(::hdmap_proto::Vector3d* high) {
  delete high_;
  high_ = high;
  if (high) {
    set_has_high();
  } else {
    clear_has_high();
  }
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Header.high)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Map::kHeaderFieldNumber;
const int Map::kSectionsFieldNumber;
const int Map::kZonesFieldNumber;
const int Map::kObstaclesFieldNumber;
const int Map::kSegPointFieldNumber;
const int Map::kSlopesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Map::Map()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap_proto.Map)
}

void Map::InitAsDefaultInstance() {
  header_ = const_cast< ::hdmap_proto::Header*>(&::hdmap_proto::Header::default_instance());
  slopes_ = const_cast< ::hdmap_proto::SlopeSets*>(&::hdmap_proto::SlopeSets::default_instance());
}

Map::Map(const Map& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hdmap_proto.Map)
}

void Map::SharedCtor() {
  _cached_size_ = 0;
  header_ = NULL;
  slopes_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Map::~Map() {
  // @@protoc_insertion_point(destructor:hdmap_proto.Map)
  SharedDtor();
}

void Map::SharedDtor() {
  if (this != default_instance_) {
    delete header_;
    delete slopes_;
  }
}

void Map::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Map::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Map_descriptor_;
}

const Map& Map::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2eproto();
  return *default_instance_;
}

Map* Map::default_instance_ = NULL;

Map* Map::New(::google::protobuf::Arena* arena) const {
  Map* n = new Map;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Map::Clear() {
// @@protoc_insertion_point(message_clear_start:hdmap_proto.Map)
  if (_has_bits_[0 / 32] & 33u) {
    if (has_header()) {
      if (header_ != NULL) header_->::hdmap_proto::Header::Clear();
    }
    if (has_slopes()) {
      if (slopes_ != NULL) slopes_->::hdmap_proto::SlopeSets::Clear();
    }
  }
  sections_.Clear();
  zones_.Clear();
  obstacles_.Clear();
  segpoint_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Map::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap_proto.Map)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .hdmap_proto.Header header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sections;
        break;
      }

      // repeated .hdmap_proto.Section sections = 2;
      case 2: {
        if (tag == 18) {
         parse_sections:
          DO_(input->IncrementRecursionDepth());
         parse_loop_sections:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_sections()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_sections;
        if (input->ExpectTag(26)) goto parse_loop_zones;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .hdmap_proto.Zone zones = 3;
      case 3: {
        if (tag == 26) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_zones:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_zones()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_zones;
        if (input->ExpectTag(34)) goto parse_loop_obstacles;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .hdmap_proto.Obstacle obstacles = 4;
      case 4: {
        if (tag == 34) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_obstacles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_obstacles()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_obstacles;
        if (input->ExpectTag(42)) goto parse_loop_segPoint;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .hdmap_proto.SemanticPoint segPoint = 5;
      case 5: {
        if (tag == 42) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_segPoint:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_segpoint()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_segPoint;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(50)) goto parse_slopes;
        break;
      }

      // optional .hdmap_proto.SlopeSets slopes = 6;
      case 6: {
        if (tag == 50) {
         parse_slopes:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_slopes()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap_proto.Map)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap_proto.Map)
  return false;
#undef DO_
}

void Map::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap_proto.Map)
  // optional .hdmap_proto.Header header = 1;
  if (has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // repeated .hdmap_proto.Section sections = 2;
  for (unsigned int i = 0, n = this->sections_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->sections(i), output);
  }

  // repeated .hdmap_proto.Zone zones = 3;
  for (unsigned int i = 0, n = this->zones_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->zones(i), output);
  }

  // repeated .hdmap_proto.Obstacle obstacles = 4;
  for (unsigned int i = 0, n = this->obstacles_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->obstacles(i), output);
  }

  // repeated .hdmap_proto.SemanticPoint segPoint = 5;
  for (unsigned int i = 0, n = this->segpoint_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->segpoint(i), output);
  }

  // optional .hdmap_proto.SlopeSets slopes = 6;
  if (has_slopes()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->slopes_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap_proto.Map)
}

::google::protobuf::uint8* Map::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hdmap_proto.Map)
  // optional .hdmap_proto.Header header = 1;
  if (has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->header_, false, target);
  }

  // repeated .hdmap_proto.Section sections = 2;
  for (unsigned int i = 0, n = this->sections_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->sections(i), false, target);
  }

  // repeated .hdmap_proto.Zone zones = 3;
  for (unsigned int i = 0, n = this->zones_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->zones(i), false, target);
  }

  // repeated .hdmap_proto.Obstacle obstacles = 4;
  for (unsigned int i = 0, n = this->obstacles_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->obstacles(i), false, target);
  }

  // repeated .hdmap_proto.SemanticPoint segPoint = 5;
  for (unsigned int i = 0, n = this->segpoint_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, this->segpoint(i), false, target);
  }

  // optional .hdmap_proto.SlopeSets slopes = 6;
  if (has_slopes()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->slopes_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap_proto.Map)
  return target;
}

int Map::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:hdmap_proto.Map)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 33u) {
    // optional .hdmap_proto.Header header = 1;
    if (has_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->header_);
    }

    // optional .hdmap_proto.SlopeSets slopes = 6;
    if (has_slopes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->slopes_);
    }

  }
  // repeated .hdmap_proto.Section sections = 2;
  total_size += 1 * this->sections_size();
  for (int i = 0; i < this->sections_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sections(i));
  }

  // repeated .hdmap_proto.Zone zones = 3;
  total_size += 1 * this->zones_size();
  for (int i = 0; i < this->zones_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->zones(i));
  }

  // repeated .hdmap_proto.Obstacle obstacles = 4;
  total_size += 1 * this->obstacles_size();
  for (int i = 0; i < this->obstacles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->obstacles(i));
  }

  // repeated .hdmap_proto.SemanticPoint segPoint = 5;
  total_size += 1 * this->segpoint_size();
  for (int i = 0; i < this->segpoint_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->segpoint(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Map::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hdmap_proto.Map)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Map* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Map>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hdmap_proto.Map)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hdmap_proto.Map)
    MergeFrom(*source);
  }
}

void Map::MergeFrom(const Map& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hdmap_proto.Map)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  sections_.MergeFrom(from.sections_);
  zones_.MergeFrom(from.zones_);
  obstacles_.MergeFrom(from.obstacles_);
  segpoint_.MergeFrom(from.segpoint_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_header()) {
      mutable_header()->::hdmap_proto::Header::MergeFrom(from.header());
    }
    if (from.has_slopes()) {
      mutable_slopes()->::hdmap_proto::SlopeSets::MergeFrom(from.slopes());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Map::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hdmap_proto.Map)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Map::CopyFrom(const Map& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hdmap_proto.Map)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Map::IsInitialized() const {

  if (has_header()) {
    if (!this->header_->IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->sections())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->zones())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->obstacles())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->segpoint())) return false;
  if (has_slopes()) {
    if (!this->slopes_->IsInitialized()) return false;
  }
  return true;
}

void Map::Swap(Map* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Map::InternalSwap(Map* other) {
  std::swap(header_, other->header_);
  sections_.UnsafeArenaSwap(&other->sections_);
  zones_.UnsafeArenaSwap(&other->zones_);
  obstacles_.UnsafeArenaSwap(&other->obstacles_);
  segpoint_.UnsafeArenaSwap(&other->segpoint_);
  std::swap(slopes_, other->slopes_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Map::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Map_descriptor_;
  metadata.reflection = Map_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Map

// optional .hdmap_proto.Header header = 1;
bool Map::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Map::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
void Map::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
void Map::clear_header() {
  if (header_ != NULL) header_->::hdmap_proto::Header::Clear();
  clear_has_header();
}
const ::hdmap_proto::Header& Map::header() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
::hdmap_proto::Header* Map::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::hdmap_proto::Header;
  }
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.header)
  return header_;
}
::hdmap_proto::Header* Map::release_header() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Map.header)
  clear_has_header();
  ::hdmap_proto::Header* temp = header_;
  header_ = NULL;
  return temp;
}
void Map::set_allocated_header(::hdmap_proto::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Map.header)
}

// repeated .hdmap_proto.Section sections = 2;
int Map::sections_size() const {
  return sections_.size();
}
void Map::clear_sections() {
  sections_.Clear();
}
const ::hdmap_proto::Section& Map::sections(int index) const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.sections)
  return sections_.Get(index);
}
::hdmap_proto::Section* Map::mutable_sections(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.sections)
  return sections_.Mutable(index);
}
::hdmap_proto::Section* Map::add_sections() {
  // @@protoc_insertion_point(field_add:hdmap_proto.Map.sections)
  return sections_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap_proto::Section >*
Map::mutable_sections() {
  // @@protoc_insertion_point(field_mutable_list:hdmap_proto.Map.sections)
  return &sections_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::Section >&
Map::sections() const {
  // @@protoc_insertion_point(field_list:hdmap_proto.Map.sections)
  return sections_;
}

// repeated .hdmap_proto.Zone zones = 3;
int Map::zones_size() const {
  return zones_.size();
}
void Map::clear_zones() {
  zones_.Clear();
}
const ::hdmap_proto::Zone& Map::zones(int index) const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.zones)
  return zones_.Get(index);
}
::hdmap_proto::Zone* Map::mutable_zones(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.zones)
  return zones_.Mutable(index);
}
::hdmap_proto::Zone* Map::add_zones() {
  // @@protoc_insertion_point(field_add:hdmap_proto.Map.zones)
  return zones_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap_proto::Zone >*
Map::mutable_zones() {
  // @@protoc_insertion_point(field_mutable_list:hdmap_proto.Map.zones)
  return &zones_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::Zone >&
Map::zones() const {
  // @@protoc_insertion_point(field_list:hdmap_proto.Map.zones)
  return zones_;
}

// repeated .hdmap_proto.Obstacle obstacles = 4;
int Map::obstacles_size() const {
  return obstacles_.size();
}
void Map::clear_obstacles() {
  obstacles_.Clear();
}
const ::hdmap_proto::Obstacle& Map::obstacles(int index) const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.obstacles)
  return obstacles_.Get(index);
}
::hdmap_proto::Obstacle* Map::mutable_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.obstacles)
  return obstacles_.Mutable(index);
}
::hdmap_proto::Obstacle* Map::add_obstacles() {
  // @@protoc_insertion_point(field_add:hdmap_proto.Map.obstacles)
  return obstacles_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap_proto::Obstacle >*
Map::mutable_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:hdmap_proto.Map.obstacles)
  return &obstacles_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::Obstacle >&
Map::obstacles() const {
  // @@protoc_insertion_point(field_list:hdmap_proto.Map.obstacles)
  return obstacles_;
}

// repeated .hdmap_proto.SemanticPoint segPoint = 5;
int Map::segpoint_size() const {
  return segpoint_.size();
}
void Map::clear_segpoint() {
  segpoint_.Clear();
}
const ::hdmap_proto::SemanticPoint& Map::segpoint(int index) const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.segPoint)
  return segpoint_.Get(index);
}
::hdmap_proto::SemanticPoint* Map::mutable_segpoint(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.segPoint)
  return segpoint_.Mutable(index);
}
::hdmap_proto::SemanticPoint* Map::add_segpoint() {
  // @@protoc_insertion_point(field_add:hdmap_proto.Map.segPoint)
  return segpoint_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap_proto::SemanticPoint >*
Map::mutable_segpoint() {
  // @@protoc_insertion_point(field_mutable_list:hdmap_proto.Map.segPoint)
  return &segpoint_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap_proto::SemanticPoint >&
Map::segpoint() const {
  // @@protoc_insertion_point(field_list:hdmap_proto.Map.segPoint)
  return segpoint_;
}

// optional .hdmap_proto.SlopeSets slopes = 6;
bool Map::has_slopes() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Map::set_has_slopes() {
  _has_bits_[0] |= 0x00000020u;
}
void Map::clear_has_slopes() {
  _has_bits_[0] &= ~0x00000020u;
}
void Map::clear_slopes() {
  if (slopes_ != NULL) slopes_->::hdmap_proto::SlopeSets::Clear();
  clear_has_slopes();
}
const ::hdmap_proto::SlopeSets& Map::slopes() const {
  // @@protoc_insertion_point(field_get:hdmap_proto.Map.slopes)
  return slopes_ != NULL ? *slopes_ : *default_instance_->slopes_;
}
::hdmap_proto::SlopeSets* Map::mutable_slopes() {
  set_has_slopes();
  if (slopes_ == NULL) {
    slopes_ = new ::hdmap_proto::SlopeSets;
  }
  // @@protoc_insertion_point(field_mutable:hdmap_proto.Map.slopes)
  return slopes_;
}
::hdmap_proto::SlopeSets* Map::release_slopes() {
  // @@protoc_insertion_point(field_release:hdmap_proto.Map.slopes)
  clear_has_slopes();
  ::hdmap_proto::SlopeSets* temp = slopes_;
  slopes_ = NULL;
  return temp;
}
void Map::set_allocated_slopes(::hdmap_proto::SlopeSets* slopes) {
  delete slopes_;
  slopes_ = slopes;
  if (slopes) {
    set_has_slopes();
  } else {
    clear_has_slopes();
  }
  // @@protoc_insertion_point(field_set_allocated:hdmap_proto.Map.slopes)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap_proto

// @@protoc_insertion_point(global_scope)
